### ISSUE TITLE
大佬能分享一下原理图吗🤒🤒

### ISSUE THREAD

**Issue by jingyang-huang** [ckois/cs5463_diansai_Smart-Power-Plug#1]

**Comment by ckois** [comment]
原版不小心弄丢了emm，原理图差不多是这个样子，稍微改改就能用，只用了一个按键，引脚稍微改了改，改一下网络标签就可以了，在picture文件里有原理图引脚截图
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上7:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jingyang-huang** [comment]
抱歉没有收到原理图的图片附件啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月3日(星期五) 晚上7:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)





 原版不小心弄丢了emm，原理图差不多是这个样子，稍微改改就能用，只用了一个按键，引脚稍微改了改，改一下网络标签就可以了，在picture文件里有原理图引脚截图 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年12月3日(星期五) 晚上7:47 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1) 
 
 
 
 
 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ckois** [comment]
[CS5463.pdf](https://github.com/ckois/cs5463_diansai_Smart-Power-Plug/files/7649439/CS5463.pdf)

**Comment by jingyang-huang** [comment]
收到，谢谢大佬。后面我做完了把软件部分更新一下，预计会加入我自己的一些功能如宿舍大功率诊断等




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上8:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)





 
CS5463.pdf
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ckois** [comment]
更新了一下库里的内容，上传了点cs5463的资料，做的时候可以看一下，因为电赛时间比较短，当时我做的很水哈哈哈，估计要重新写很多位置


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上7:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)





 抱歉没有收到原理图的图片附件啊 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年12月3日(星期五) 晚上7:54 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1) 
 
 
 
 
 
  原版不小心弄丢了emm，原理图差不多是这个样子，稍微改改就能用，只用了一个按键，引脚稍微改了改，改一下网络标签就可以了，在picture文件里有原理图引脚截图  
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年12月3日(星期五) 晚上7:47  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)  
   
   
   
   
   
     
  —  
  You are receiving this because you are subscribed to this thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jingyang-huang** [comment]
又看了一下原理图，有几个问题想请教一下（电路知识不太好）：
1.P1的端子引出是不是能直接获得电流互感器输出的电流经过R11后的电压呢，但是按照我的理解应该是直接接R11两端然后获得交流电流的电压，如果也是为了获取交流电压的话能够一端接交流输出、另一端接地吗？
2.看原理图中有两个座子，但是成品图似乎没有使用座子直接焊在了板子上。那请问电阻R4和R5还需要焊接吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上8:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)





 更新了一下库里的内容，上传了点cs5463的资料，做的时候可以看一下，因为电赛时间比较短，当时我做的很水哈哈哈，估计要重新写很多位置 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年12月3日(星期五) 晚上7:59 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1) 
 
 
 
 
 
  抱歉没有收到原理图的图片附件啊  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年12月3日(星期五) 晚上7:54  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)  
   
   
   
   
   
   原版不小心弄丢了emm，原理图差不多是这个样子，稍微改改就能用，只用了一个按键，引脚稍微改了改，改一下网络标签就可以了，在picture文件里有原理图引脚截图   
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年12月3日(星期五) 晚上7:47   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;[ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)   
     
     
     
     
     
       
   —   
   You are receiving this because you are subscribed to this thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ckois** [comment]
1，信号必须要经过耦合器，我感觉你的意思是采用采样电阻的方法，那样的话，很不安全，直接接在了芯片上
2，需要焊接，这两个电阻的作用是限流，互感器最大允许通过电流是毫安级的
3，那两个座子可以画在板子上，当时做的时候没画上
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上8:44
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)





 又看了一下原理图，有几个问题想请教一下（电路知识不太好）： 
 1.P1的端子引出是不是能直接获得电流互感器输出的电流经过R11后的电压呢，但是按照我的理解应该是直接接R11两端然后获得交流电流的电压，如果也是为了获取交流电压的话能够一端接交流输出、另一端接地吗？ 
 2.看原理图中有两个座子，但是成品图似乎没有使用座子直接焊在了板子上。那请问电阻R4和R5还需要焊接吗？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年12月3日(星期五) 晚上8:30 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1) 
 
 
 
 
 
  更新了一下库里的内容，上传了点cs5463的资料，做的时候可以看一下，因为电赛时间比较短，当时我做的很水哈哈哈，估计要重新写很多位置  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年12月3日(星期五) 晚上7:59  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)  
   
   
   
   
   
   抱歉没有收到原理图的图片附件啊   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: ***@***.***&amp;amp;amp;gt;;    
   发送时间: 2021年12月3日(星期五) 晚上7:54   
   收件人: ***@***.***&amp;amp;amp;gt;;    
   抄送: ***@***.***&amp;amp;amp;gt;; ***@***.***&amp;amp;amp;gt;;    
   主题: Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)   
     
     
     
     
     
    原版不小心弄丢了emm，原理图差不多是这个样子，稍微改改就能用，只用了一个按键，引脚稍微改了改，改一下网络标签就可以了，在picture文件里有原理图引脚截图    
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年12月3日(星期五) 晚上7:47    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;[ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)    
       
       
       
       
       
         
    —    
    You are receiving this because you are subscribed to this thread.    
    Reply to this email directly, view it on GitHub, or unsubscribe.    
    Triage notifications on the go with GitHub Mobile for iOS or Android.    
   —   
   You are receiving this because you authored the thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jingyang-huang** [comment]
学习到了，另外还有两个关于元件的问题：
1.在淘宝上的参数页面看到ZMPT107的采样电阻为50欧，原理图里用的100欧，请问实际使用下来有问题吗？
2.在元器件商城里没有搜索到THWC102W，请问这个电流互感器还有什么替代吗？如ZMCT102C，ZMCT103C。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上8:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)





 1，信号必须要经过耦合器，我感觉你的意思是采用采样电阻的方法，那样的话，很不安全，直接接在了芯片上 
 2，需要焊接，这两个电阻的作用是限流，互感器最大允许通过电流是毫安级的 
 3，那两个座子可以画在板子上，当时做的时候没画上 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年12月3日(星期五) 晚上8:44 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1) 
 
 
 
 
 
  又看了一下原理图，有几个问题想请教一下（电路知识不太好）：  
  1.P1的端子引出是不是能直接获得电流互感器输出的电流经过R11后的电压呢，但是按照我的理解应该是直接接R11两端然后获得交流电流的电压，如果也是为了获取交流电压的话能够一端接交流输出、另一端接地吗？  
  2.看原理图中有两个座子，但是成品图似乎没有使用座子直接焊在了板子上。那请问电阻R4和R5还需要焊接吗？  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年12月3日(星期五) 晚上8:30  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)  
   
   
   
   
   
   更新了一下库里的内容，上传了点cs5463的资料，做的时候可以看一下，因为电赛时间比较短，当时我做的很水哈哈哈，估计要重新写很多位置   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年12月3日(星期五) 晚上7:59   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)   
     
     
     
     
     
    抱歉没有收到原理图的图片附件啊    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人: ***@***.***&amp;amp;amp;amp;gt;;     
    发送时间: 2021年12月3日(星期五) 晚上7:54    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;     
    抄送: ***@***.***&amp;amp;amp;amp;gt;; ***@***.***&amp;amp;amp;amp;gt;;     
    主题: Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)    
       
       
       
       
       
     原版不小心弄丢了emm，原理图差不多是这个样子，稍微改改就能用，只用了一个按键，引脚稍微改了改，改一下网络标签就可以了，在picture文件里有原理图引脚截图     
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2021年12月3日(星期五) 晚上7:47     
     ***@***.***&amp;amp;amp;amp;amp;gt;;     
     ***@***.***&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;[ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)     
         
         
         
         
         
           
     —     
     You are receiving this because you are subscribed to this thread.     
     Reply to this email directly, view it on GitHub, or unsubscribe.     
     Triage notifications on the go with GitHub Mobile for iOS or Android.     
    —    
    You are receiving this because you authored the thread.    
    Reply to this email directly, view it on GitHub, or unsubscribe.    
    Triage notifications on the go with GitHub Mobile for iOS or Android.    
   —   
   You are receiving this because you commented.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you modified the open/close state. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ckois** [comment]
当时我们用的电流互感器是DL-CT1005A 10A/5mA的，采样电阻阻值大小尽量不要变，变的话数量级不变就行，程序里进行参数修正吧


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上9:16
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)





 学习到了，另外还有两个关于元件的问题： 
 1.在淘宝上的参数页面看到ZMPT107的采样电阻为50欧，原理图里用的100欧，请问实际使用下来有问题吗？ 
 2.在元器件商城里没有搜索到THWC102W，请问这个电流互感器还有什么替代吗？如ZMCT102C，ZMCT103C。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年12月3日(星期五) 晚上8:54 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1) 
 
 
 
 
 
  1，信号必须要经过耦合器，我感觉你的意思是采用采样电阻的方法，那样的话，很不安全，直接接在了芯片上  
  2，需要焊接，这两个电阻的作用是限流，互感器最大允许通过电流是毫安级的  
  3，那两个座子可以画在板子上，当时做的时候没画上  
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年12月3日(星期五) 晚上8:44  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)  
   
   
   
   
   
   又看了一下原理图，有几个问题想请教一下（电路知识不太好）：   
   1.P1的端子引出是不是能直接获得电流互感器输出的电流经过R11后的电压呢，但是按照我的理解应该是直接接R11两端然后获得交流电流的电压，如果也是为了获取交流电压的话能够一端接交流输出、另一端接地吗？   
   2.看原理图中有两个座子，但是成品图似乎没有使用座子直接焊在了板子上。那请问电阻R4和R5还需要焊接吗？   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年12月3日(星期五) 晚上8:30   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)   
     
     
     
     
     
    更新了一下库里的内容，上传了点cs5463的资料，做的时候可以看一下，因为电赛时间比较短，当时我做的很水哈哈哈，估计要重新写很多位置    
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年12月3日(星期五) 晚上7:59    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)    
       
       
       
       
       
     抱歉没有收到原理图的图片附件啊     
         
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人: ***@***.***&amp;amp;amp;amp;amp;gt;;      
     发送时间: 2021年12月3日(星期五) 晚上7:54     
     收件人: ***@***.***&amp;amp;amp;amp;amp;gt;;      
     抄送: ***@***.***&amp;amp;amp;amp;amp;gt;; ***@***.***&amp;amp;amp;amp;amp;gt;;      
     主题: Re: [ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)     
         
         
         
         
         
      原版不小心弄丢了emm，原理图差不多是这个样子，稍微改改就能用，只用了一个按键，引脚稍微改了改，改一下网络标签就可以了，在picture文件里有原理图引脚截图      
      ------------------&amp;amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;amp;nbsp;------------------      
      发件人:                                                                                                                        "ckois/cs5463_diansai_Smart-Power-Plug"                                                                                    ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      发送时间:&amp;amp;amp;amp;amp;amp;nbsp;2021年12月3日(星期五) 晚上7:47      
      ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      主题:&amp;amp;amp;amp;amp;amp;nbsp;[ckois/cs5463_diansai_Smart-Power-Plug] 大佬能分享一下原理图吗🤒🤒 (Issue #1)      
           
           
           
           
           
             
      —      
      You are receiving this because you are subscribed to this thread.      
      Reply to this email directly, view it on GitHub, or unsubscribe.      
      Triage notifications on the go with GitHub Mobile for iOS or Android.      
     —     
     You are receiving this because you authored the thread.     
     Reply to this email directly, view it on GitHub, or unsubscribe.     
     Triage notifications on the go with GitHub Mobile for iOS or Android.     
    —    
    You are receiving this because you commented.    
    Reply to this email directly, view it on GitHub, or unsubscribe.    
    Triage notifications on the go with GitHub Mobile for iOS or Android.    
   —   
   You are receiving this because you authored the thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
   Triage notifications on the go with GitHub Mobile for iOS or Android.   
  —  
  You are receiving this because you modified the open/close state.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
